version: 0.2
phases:
  build:
    commands:
      - gradle build
artifacts:
  files:
  commands:
    ls ./build/libs/    
    -echo files........
    - echo $CODEBUILD_SRC_DIR
    - 'build/*'
  name: $(AWS_REGION)-$(date +%Y-%m-%d)
