version: 0.2
phases:
  build:
    commands:
      - gradle build
artifacts:
  files:
    -echo files........
    - echo $CODEBUILD_SRC_DIR
    - '$CODEBUILD_SRC_DIR/build/libs/*'
  name: $(AWS_REGION)-$(date +%Y-%m-%d)